### ISSUE TITLE
PyPI seems to have older version of the API

### ISSUE THREAD

**Issue by isFakeAccount** [scrubjay55/Reddit_ChatBot_Python#2]
READMe needs to be updated as you moved the functions from chatbot to WebSocket client. This is the code that I was able to get working

```
from Reddit_ChatBot_Python import RedditAuthentication, ChatBot

reddit_authentication = RedditAuthentication.PasswordAuth(reddit_username=username, reddit_password=password)

chatbot = ChatBot(authentication=reddit_authentication)
websocket_client = chatbot.WebSocketClient

@websocket_client.after_message_hook()
def hello(resp):
    websocket_client.send_message("General Kenobi!", resp.channel_url)
    return True

websocket_client.set_respond_hook(input_="Hi", response="Hello {nickname}! sup?", limited_to_users=None,
                                  lower_the_input=False, exclude_itself=True, must_be_equal=True)

websocket_client.run_4ever(auto_reconnect=True)
```

However one thing I noticed the bot replies to the same message 3 times. Is there a way to get rid of this denounce thing? This is the output I get
```
Vault-TecTradingCo@: Hello there!
Fallout76MktPlBot@: General Kenobi!
Fallout76MktPlBot@: General Kenobi!
Fallout76MktPlBot@: General Kenobi!
```

**Comment by isFakeAccount** [comment]
I was able to fix the 3 times reply by changing the code to this
```
@websocket_client.after_message_hook()
def hello(resp):
    if resp.user.name == username:
        return True
    websocket_client.send_message("General Kenobi!", resp.channel_url)
    time.sleep(5)
    return True
```
It seems `exclude_itself=True` in the following line is not really working or perhaps it is not what I am thinking it is
```
websocket_client.set_respond_hook(input_="Hi", response="Hello {nickname}! sup?", limited_to_users=None,
                                  lower_the_input=False, exclude_itself=True, must_be_equal=True)
```

**Comment by isFakeAccount** [comment]
Ah ok I was able to figure out the issue. It seems PiPy has the older version of this API and the new documentation doesn't work on it.

**Comment by scrubjay55** [comment]
Yep. You can refer to the readme on the pypi for the current version :)

**Comment by isFakeAccount** [comment]
I have one question. If a user sends me a DM. Unless I go and accept their chat invite. The hooks don't read messages. Is there a way to accept users automatically?

**Comment by isFakeAccount** [comment]
The endpoint seems to be 

```
https://sendbirdproxyk8s.chat.redditmedia.com/v3/group_channels/{mesg_id}/accept
```

**Comment by scrubjay55** [comment]
I actually implemented a big portion of the rest of the API including accepting DMs. They are local tho I will push them when I get the chance.

**Comment by scrubjay55** [comment]
aight pushed

**Comment by isFakeAccount** [comment]
thank you :)
