### ISSUE TITLE
Can this work with OAuth2 authorization?

### ISSUE THREAD

**Issue by Nikolak47** [scrubjay55/Reddit_ChatBot_Python#4]
Can I authenticate myself through oauth (with client_id and client_secret), or it must be through username + password?

**Comment by scrubjay55** [comment]
unfortunately no. the api token obtained from the registered app from reddit isnt scoped for the sendbird endpoint as it's not a public part of the api.

**Comment by Nikolak47** [comment]
What kind of API you are talking about?
`works either with reddit username & password or the api token (not a regular one you get from your registered app as it's not fully scoped)`

**Comment by scrubjay55** [comment]
I am talking about the reddit API. Like I mentioned in readme there, it's not possible. When you try to get a sendbird chat api token with the api token you generated with client id and client secret, it will send back an unauthorized error.

TokenAuth is for self obtained fully scoped api keys.

**Comment by Nikolak47** [comment]
Thanks for the answer!
How can I obtain this Fully Scoped Self Obtained API key? Is it from SendBird, from Reddit or from the Reddit mobile app?
Can you please explain more here? 
Thanks! :)

**Comment by scrubjay55** [comment]
Login into your account from a web browser and see the request headers with browser's devtools it will be there. Or you can MITM the official app.

This is where I obtain the fully scoped token: https://github.com/scrubjay55/Reddit_ChatBot_Python/blob/master/Reddit_ChatBot_Python/reddit_auth.py

**Comment by scrubjay55** [comment]
Login into your account from a web browser and see the request headers with browser's devtools it will be there. Or you can MITM the official app.

This is where I obtain the fully scoped token from the username and password: https://github.com/scrubjay55/Reddit_ChatBot_Python/blob/master/Reddit_ChatBot_Python/reddit_auth.py
